// app/demo/assets.js
export function getDemoAssets() {
  const now = Date.now();
  const days = (d) => new Date(now - d * 86400000).toISOString();

  return [
    {
      id: "demo-1",
      name: "Registre Paie 2024",
      department: "Ressources Humaines",
      owner: "Service RH",
      description: "Registre mensuel de paie",
      origine: "Interne",
      destination: "Direction & RH",
      formatPapier: true,
      formatElectronique: true,
      dp: true,
      cScore: 4, iScore: 5, aScore: 3, tScore: 4,
      sensibilite: 4,
      impactOp: 3, impactConf: 4, impactRep: 3, impactFin: 4,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 16, risqueResiduel: 7, risqueAccepte: false,
      analyseRisque: "Contrôles d’accès et chiffrement",
      mesuresExistantes: "MFA, sauvegardes",
      risk: "Élevé",
      classification: "Secret",
      fileName: null,
      fileUrl: null,
      conformite: "Conforme",
      createdAt: days(0),
      processus: "Paie",
    },
    {
      id: "demo-2",
      name: "Budget Prévisionnel 2025 (V1)",
      department: "Finances",
      owner: "Service Financier",
      description: "Projection annuelle initiale",
      origine: "Interne",
      destination: "Direction Générale",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 3, iScore: 4, aScore: 3, tScore: 3,
      sensibilite: 3,
      impactOp: 2, impactConf: 3, impactRep: 2, impactFin: 4,
      probabilite: 2, exposition: 2, attenuation: 1,
      risqueBrut: 12, risqueResiduel: 5, risqueAccepte: true,
      analyseRisque: "Accès restreint, journalisation",
      mesuresExistantes: "RBAC, VPN",
      risk: "Moyen",
      classification: "Interne",
      fileName: null,
      fileUrl: null,
      conformite: "Conforme",
      createdAt: days(2),
      processus: "Budgétisation",
    },

    // 👇 Add many more (examples):
    {
      id: "demo-3",
      name: "Contrats Fournisseurs 2024",
      department: "Juridique",
      owner: "Dépt. Juridique",
      description: "Contrats et avenants signés",
      origine: "Externe",
      destination: "Direction & Juridique",
      formatPapier: true,
      formatElectronique: true,
      dp: true,
      cScore: 4, iScore: 4, aScore: 2, tScore: 3,
      sensibilite: 4,
      impactOp: 2, impactConf: 4, impactRep: 4, impactFin: 3,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 16, risqueResiduel: 8, risqueAccepte: false,
      analyseRisque: "Archivage sécurisé, signature électronique",
      mesuresExistantes: "Coffre-fort numérique",
      risk: "Élevé",
      classification: "Confidentiel",
      conformite: "Non Conforme",
      createdAt: days(5),
      processus: "Conformité Légale",
    },
    {
      id: "demo-4",
      name: "Plan de Communication Q3",
      department: "Marketing",
      owner: "Service Communication",
      description: "Campagnes et messages clé",
      origine: "Interne",
      destination: "Marketing",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 2, iScore: 3, aScore: 3, tScore: 2,
      sensibilite: 2,
      impactOp: 2, impactConf: 2, impactRep: 2, impactFin: 2,
      probabilite: 2, exposition: 1, attenuation: 2,
      risqueBrut: 8, risqueResiduel: 3, risqueAccepte: true,
      analyseRisque: "Validation avant diffusion",
      mesuresExistantes: "Workflow d’approbation",
      risk: "Faible",
      classification: "Public",
      conformite: "Conforme",
      createdAt: days(8),
      processus: "Communication",
    },
    {
      id: "demo-5",
      name: "Rapport Audit Sécu - Juin",
      department: "Conformité & Sécurité",
      owner: "Cellule Conformité",
      description: "Résultats tests d’intrusion",
      origine: "Interne",
      destination: "Direction & IT",
      formatPapier: false,
      formatElectronique: true,
      dp: true,
      cScore: 5, iScore: 4, aScore: 3, tScore: 4,
      sensibilite: 5,
      impactOp: 3, impactConf: 5, impactRep: 4, impactFin: 4,
      probabilite: 3, exposition: 3, attenuation: 2,
      risqueBrut: 25, risqueResiduel: 10, risqueAccepte: false,
      analyseRisque: "Correctifs prioritaires",
      mesuresExistantes: "SIEM, EDR",
      risk: "Élevé",
      classification: "Très Secret",
      conformite: "Non Conforme",
      createdAt: days(11),
      processus: "Audit Sécurité",
    },
    {
      id: "demo-6",
      name: "Procédures Helpdesk",
      department: "Informatique",
      owner: "Équipe IT",
      description: "Connaissances et SOP",
      origine: "Interne",
      destination: "IT",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 2, iScore: 3, aScore: 4, tScore: 2,
      sensibilite: 2,
      impactOp: 3, impactConf: 2, impactRep: 2, impactFin: 1,
      probabilite: 2, exposition: 2, attenuation: 3,
      risqueBrut: 8, risqueResiduel: 4, risqueAccepte: true,
      analyseRisque: "Sauvegardes régulières",
      mesuresExistantes: "Wiki interne",
      risk: "Faible",
      classification: "Interne",
      conformite: "Conforme",
      createdAt: days(14),
      processus: "Support IT",
    },
    {
      id: "demo-7",
      name: "Feuille de Route 2025",
      department: "Direction Générale",
      owner: "DG",
      description: "Vision stratégique et KPIs",
      origine: "Interne",
      destination: "Direction",
      formatPapier: false,
      formatElectronique: true,
      dp: true,
      cScore: 4, iScore: 3, aScore: 2, tScore: 3,
      sensibilite: 4,
      impactOp: 3, impactConf: 4, impactRep: 4, impactFin: 3,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 16, risqueResiduel: 6, risqueAccepte: false,
      analyseRisque: "Diffusion restreinte",
      mesuresExistantes: "DLP",
      risk: "Moyen",
      classification: "Confidentiel",
      conformite: "Conforme",
      createdAt: days(18),
      processus: "Stratégie",
    },
    {
      id: "demo-8",
      name: "Planning Logistique Été",
      department: "Opérations",
      owner: "Dépt. Opérations",
      description: "Ressources & horaires",
      origine: "Interne",
      destination: "Opérations",
      formatPapier: true,
      formatElectronique: true,
      dp: false,
      cScore: 2, iScore: 2, aScore: 3, tScore: 2,
      sensibilite: 2,
      impactOp: 3, impactConf: 1, impactRep: 2, impactFin: 2,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 8, risqueResiduel: 4, risqueAccepte: true,
      analyseRisque: "Contrôles d’accès locaux",
      mesuresExistantes: "Badges",
      risk: "Faible",
      classification: "Interne",
      conformite: "Conforme",
      createdAt: days(21),
      processus: "Gestion Courante",
    },
    {
      id: "demo-9",
      name: "Dossiers Employés",
      department: "Ressources Humaines",
      owner: "Service RH",
      description: "Données personnelles",
      origine: "Interne",
      destination: "RH",
      formatPapier: true,
      formatElectronique: true,
      dp: true,
      cScore: 5, iScore: 4, aScore: 3, tScore: 4,
      sensibilite: 5,
      impactOp: 3, impactConf: 5, impactRep: 4, impactFin: 3,
      probabilite: 3, exposition: 3, attenuation: 2,
      risqueBrut: 25, risqueResiduel: 12, risqueAccepte: false,
      analyseRisque: "Chiffrement au repos",
      mesuresExistantes: "Cloisonnement réseaux",
      risk: "Élevé",
      classification: "Secret",
      conformite: "Non Conforme",
      createdAt: days(25),
      processus: "Paie",
    },
    {
      id: "demo-10",
      name: "Politique Sécurité v3",
      department: "Conformité & Sécurité",
      owner: "RSSI",
      description: "Normes & exigences internes",
      origine: "Interne",
      destination: "Tous",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 3, iScore: 3, aScore: 3, tScore: 3,
      sensibilite: 3,
      impactOp: 2, impactConf: 3, impactRep: 3, impactFin: 2,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 12, risqueResiduel: 6, risqueAccepte: true,
      analyseRisque: "Revue annuelle",
      mesuresExistantes: "Formation sécurité",
      risk: "Moyen",
      classification: "Interne",
      conformite: "Conforme",
      createdAt: days(28),
      processus: "Audit Sécurité",
    },
    {
      id: "demo-11",
      name: "Rapport KPI Marketing",
      department: "Marketing",
      owner: "Service Communication",
      description: "Performances trimestrielles",
      origine: "Interne",
      destination: "Direction",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 2, iScore: 2, aScore: 2, tScore: 2,
      sensibilite: 2,
      impactOp: 1, impactConf: 2, impactRep: 2, impactFin: 2,
      probabilite: 2, exposition: 1, attenuation: 2,
      risqueBrut: 6, risqueResiduel: 3, risqueAccepte: true,
      analyseRisque: "Revue avant diffusion",
      mesuresExistantes: "Contrôle qualité",
      risk: "Faible",
      classification: "Public",
      conformite: "Conforme",
      createdAt: days(30),
      processus: "Communication",
    },
    {
      id: "demo-12",
      name: "Inventaire Matériel IT",
      department: "Informatique",
      owner: "Équipe IT",
      description: "Parc machines & licences",
      origine: "Interne",
      destination: "IT & Achat",
      formatPapier: false,
      formatElectronique: true,
      dp: false,
      cScore: 3, iScore: 3, aScore: 4, tScore: 3,
      sensibilite: 3,
      impactOp: 4, impactConf: 2, impactRep: 2, impactFin: 2,
      probabilite: 2, exposition: 2, attenuation: 2,
      risqueBrut: 12, risqueResiduel: 5, risqueAccepte: true,
      analyseRisque: "Sauvegardes & audits",
      mesuresExistantes: "MDM",
      risk: "Moyen",
      classification: "Interne",
      conformite: "Conforme",
      createdAt: days(33),
      processus: "Support IT",
    },
  ];
}
